# Generated by Django 5.2.1 on 2025-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organizer_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
